--- #YAML:1.0
name:               Finance-MICR-LineParser
version:            1.07
abstract:           validate and parse a check MICR string
author:
    - Leo Charre leocharre at cpan dot org
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:             1
    Cwd:              3
    Smart::Comments:  1
    Test::Simple:     0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
