# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Finance-MICR-LineParser
version:      1.05
version_from: lib/Finance/MICR/LineParser.pm
installdirs:  site
requires:
    Carp:                          0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
